export const GETTING_ALL_CUSTOMER_DETAILS = "GETTING_ALL_CUSTOMER_DETAILS";
export const GETTING_ALL_CUSTOMER_DETAILS_SUCCESS = "GETTING_ALL_CUSTOMER_DETAILS_SUCCESS";
export const GETTING_ALL_CUSTOMER_DETAILS_ERROR = "GETTING_ALL_CUSTOMER_DETAILS_ERROR";

export const DELETING_CUSTOMER = "DELETING_CUSTOMER";
export const DELETING_CUSTOMER_SUCCESS = "DELETING_CUSTOMER_SUCCESS";
export const DELETING_CUSTOMER_ERROR = "DELETING_CUSTOMER_ERROR";
export const DELETING_CUSTOMER_RESET = "DELETING_CUSTOMER_RESET";