//Seller Products Addition
export const ADDING_SELLER_PRODUCTS="ADDING_SELLER_PRODUCTS";
export const ADDING_SELLER_PRODUCTS_SUCCESS="ADDING_SELLER_PRODUCTS_SUCCESS";
export const ADDING_SELLER_PRODUCTS_ERROR="ADDING_SELLER_PRODUCTS_ERROR";
export const ADDING_SELLER_PRODUCTS_RESET="ADDING_SELLER_PRODUCTS_RESET";

export const GET_ALL_SELLER_PRODUCTS="GET_ALL_SELLER_PRODUCTS";
export const GET_ALL_SELLER_PRODUCTS_SUCCESS="GET_ALL_SELLER_PRODUCTS_SUCCESS";
export const GET_ALL_SELLER_PRODUCTS_ERROR="GET_ALL_SELLER_PRODUCTS_ERROR";

export const DELETE_SELLER_PRODUCT="DELETE_SELLER_PRODUCT";
export const DELETE_SELLER_PRODUCT_SUCCESS="DELETE_SELLER_PRODUCT_SUCCESS";
export const DELETE_SELLER_PRODUCT_ERROR="DELETE_SELLER_PRODUCT_ERROR";
export const DELETE_SELLER_PRODUCT_RESET="DELETE_SELLER_PRODUCT_RESET";

export const UPDATE_SELLER_PRODUCT="UPDATE_SELLER_PRODUCT";
export const UPDATE_SELLER_PRODUCT_SUCCESS="UPDATE_SELLER_PRODUCT_SUCCESS";
export const UPDATE_SELLER_PRODUCT_ERROR="UPDATE_SELLER_PRODUCT_ERROR";
export const UPDATE_SELLER_PRODUCT_RESET="UPDATE_SELLER_PRODUCT_RESET";