export const GETTING_ALL_PRODUCTS = "GETTING_ALL_PRODUCTS";
export const GETTING_ALL_PRODUCTS_SUCCESS = "GETTING_ALL_PRODUCTS_SUCCESS";
export const GETTING_ALL_PRODUCTS_ERROR = "GETTING_ALL_PRODUCTS_ERROR";