//User Login
export const USER_LOGIN="USER_LOGIN";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR="USER_LOGIN_ERROR";

//User Logout
export const USER_LOGOUT="USER_LOGOUT";
export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS";

//User Register
export const USER_REGISTER="USER_REGISTER";
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR="USER_REGISTER_ERROR";
export const USER_REGISTER_RESET="USER_REGISTER_RESET";

//Fetch User Details
export const FETCH_USER="FETCH_USER";
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR="FETCH_USER_ERROR";